version : "3.3"

networks:
  project:
 
volumes:
  mongo_data:

services:
 
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    networks:
      - project

  
  comment:
    container_name: comment
    ports:
      - 8084:8084
    environment:
      MONGO_URL: mongodb://mongo:27017 
      PORT_COMM: 8084
    networks:
      - project
    build:
      context: ./CommentService
      dockerfile: .dockerfile
    depends_on:
      - mongo